# Generated by Django 4.1.7 on 2023-03-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='cuantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
